#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#autostart app
sxhkd &



#res
xrandr --output Virtual-1 --mode 1360x768 &

#polybar
bspc config top_padding 26

$HOME/.config/polybar/launch.sh &
bspc config normal_border_color "#1a3d3a"
bspc config active_border_color "#4a9188"
bspc config focused_border_color "#4a9188"
bspc config presel_feedback_color "#2f6b63"
feh --bg-fill ~/Downloads/wallhaven-mlgzzy_3840x2160.png &
#compositor
picom &
